name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://741af198c5d3c612-9c974c46115a134f.jomoxc.com:9082/fs57cb1b02.a.bdydns.com/4113596937/Firmware/Flyme/meizu17_Pro/9.3.1.0/cn/20230115194440/e8acbce5/update.zip?r=ACBCNjZOXXYyUCI6HSAkAUUmUzVrEh4gOVx%2BNAUseSIBJlsxJAYXdhJVKToPbjsBAS5Dd3IrIis7Fml5WW9nSlh7VShqRkJrZwlhZl9wb1BcYAZpIEwTOjZaNWJFNCYACSBTaD8dAmY1TCQ%2FNSozHVVlAXV3RERpYAhmelpsZkkJNlJ%2FcBIUP21fYmJceGJSWG1VJSFBFj9iC2dvCCNvUAckUygmEBxoO0k1OQklOFU%3D&xcid=355d2587a0a840db874a035662a51c25&max_age=7776000&xcsched=1466217590&xclogid=10769943620529334496&xauzkey=mngx_2729ab9b72a8612c75587cd829dabd65_1732308816&f_ver=v1&auth_key=1732060416-0-0-abd95fff9f25694609ccd5df6278bb94
  ROM_NAME: Flyme
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
